version: "3.3"
services:
  api:
    container_name: zeit-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    container_name: zeit-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8001:80'
    env_file:
      - .env
